apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-production.yml
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: froze_ouster_shroud
        - name: VIRTUAL_HOST
          value: site-visit-db.workers.cloud
        image: postgres:10.0
        name: db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /db/dumps
          name: db-claim0
        - mountPath: /tmp
          name: db-claim1
        - mountPath: /var/lib/postgresql/data
          name: sitevisitroot-postgres-data
      restartPolicy: Always
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
      - name: sitevisitroot-postgres-data
        persistentVolumeClaim:
          claimName: sitevisitroot-postgres-data
status: {}
