version: '3'

volumes:
  postgres-data:
    driver: local

services:
  server:
    build: ./site_visit_server
    image: site_visit_server
    # command: bash -c "bundle exec rails s -p 8000 -b '0.0.0.0'"
    command: bundle exec rails s -p 8000 -b '0.0.0.0'
    # environment:
    #   - VIRTUAL_HOST=engine.ddx
    # volumes:
    #   - .:/site_visit_server
    depends_on:
      - db
    ports:
       - "8000:8000"

  db:
    image: postgres:10.0
    ports:
      - 5432:5432
    volumes:
      - ./db/dumps:/db/dumps
      - ./tmp:/tmp
      # # # Mount our 'restoredb' script:
      # # - ./bin/restoredb:/bin/restoredb:ro
      # # Mount our 'dumpdb' script:
      # - ./bin/dumpdb:/bin/dumpdb:ro
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
